services:
 adminer-app:
  image: adminer-alpine-ncc
  container_name: adminer-alpine-ncc
  init: true  # <--- Rất quan trọng để dọn dẹp zombie từ php-fpm và nginx
  volumes:
   - /home/git/project-docker-dev/project-test/adminer/www.conf:/etc/php/php-fpm.d/www.conf
  entrypoint: /bin/sh -c "mkdir -p /run/php-fpm; addgroup -S www-data 2>/dev/null; adduser -D -S -G www-data www-data 2>/dev/null; chown www-data:www-data /run/php-fpm; exec php-fpm -F"

